# Generated by Django 2.1.7 on 2019-04-10 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfer',
            options={'managed': True},
        ),
    ]
