# Generated by Django 2.1.7 on 2019-04-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0002_golfer_managed_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='golfer_city',
            field=models.TextField(blank=True, default='unknown'),
        ),
    ]
