# Generated by Django 2.1.7 on 2019-04-07 03:49

from django.db import migrations
import csv

class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0003_add_golfer_city'),
    ]

    def add_city_data(apps, schema_editor):
        golfer_id = 1
        try:
            input_file = open("golfersInput.csv", 'r')
            file_lines = csv.reader(input_file)
            golfers = list(file_lines)

            for golfer in golfers:
                i = golfer_id - 1
                golfer_name = golfer[0].strip()
                golfer_birthdate = golfer[1].strip()
                golfer_city = golfer[2].strip()
                golfers[i]=(golfer_name, golfer_birthdate, golfer_city)
                golfer_id = golfer_id + 1

            input_file.close()

        except IOError:
            print("File Not Found Error.")

        Golfer = apps.get_model ('golfer', 'Golfer')
        
        for name, bdate, city in golfers:
            golfer = Golfer.objects.get(golfer_name=name)
            golfer.golfer_city = city
            golfer.save()
            
    def remove_city_data (apps, schema_editor):
    
        Golfer = apps.get_model ('golfer', 'Golfer')
        Golfer.objects.update (golfer_city = 'unknown')
            
    
    operations = [
        migrations.RunPython(add_city_data, reverse_code = remove_city_data)
    ]
